apiVersion: v1
kind: Service
metadata:
  name: network-multitool
  labels:
    app: network-multitool
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: network-multitool
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: network-multitool
  name: network-multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-multitool
  template:
    metadata:
      labels:
        app: network-multitool
    spec:
      containers:
        - image: wbitt/network-multitool
          name: network-multitool
          imagePullPolicy: IfNotPresent
      serviceAccountName: netology