apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: prod
  labels:
    app: db
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: db
  name: db
  namespace: prod
spec:
  selector:
    matchLabels:
      app: db
  serviceName: "db"
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: artemsalnikov/postgres
          volumeMounts:
            - mountPath: "/data"
              name: my-volume
          ports:
            - name: postgresqlkub
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: news
      volumes:
        - name: my-volume
          persistentVolumeClaim:
            claimName: pvc