---
apiVersion: v1
kind: Service
metadata:
  name: backend-{{ .Release.Name }}
  labels:
    app: backend
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.back.port }}
    targetPort: {{ .Values.back.port }}
    protocol: TCP
  selector:
    app: backend
