---
apiVersion: v1
kind: Service
metadata:
  name: db-{{ .Release.Name }}
  labels:
    app: db
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.db.port }}
    targetPort: {{ .Values.db.port }}
    protocol: TCP
  selector:
    app: db