---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend-{{ .Release.Name }}
spec:
  replicas: {{ .Values.back.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: "{{ .Values.back.image.repository }}/{{ .Values.back.image.tag }}"
          name: backend
          imagePullPolicy: IfNotPresent
          env:
          - name: DATABASE_URL
            value: {{ .Values.back.db_url }}