apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-{{ .Release.Name }}
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.pv.capacity }}
  hostPath:
    path: /data/pv